version: '3.8'

services:
  mixtral:
    build:
      context: .
      args:
        max_jobs: 8
        nvcc_threads: 2
    container_name: mixtral
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]